### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by yarkinslav** [kaczmarj/ANTs-builds#6]
Dear Kaczmarj,

I have a problem with build ANTs docker container, here is the code:
   ```
 -- SuperBuild -   ITKv4[OK]
 CMake Error at /opt/cmake-2.8.12.2-Linux-i386/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY) (found version "1.2.3")
Call Stack (most recent call first):
  /opt/cmake-2.8.12.2-Linux-i386/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /opt/cmake-2.8.12.2-Linux-i386/share/cmake-2.8/Modules/FindZLIB.cmake:85 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  SuperBuild/External_ITKv4.cmake:112 (find_package)
  CMake/SlicerMacroCheckExternalProjectDependency.cmake:69 (include)
  SuperBuild.cmake:205 (SlicerMacroCheckExternalProjectDependency)
  CMakeLists.txt:60 (include)
```

**Comment by kaczmarj** [comment]
hi @relyativist - can you try with the updated branch https://github.com/kaczmarj/ANTs-builds/tree/add/versions ?

**Comment by yarkinslav** [comment]
Thanks for quick respond!
Sorry, I can't clearly understand: it it right command to build docker for new branch?
ants_version=v2.2.0

docker build -t ants:$ants_version \
--build-arg ants_version=$ants_version - < Dockerfile \
| tee logs/ANTs-Linux-centos6_x86_64-v${ants_version}.log

**Comment by kaczmarj** [comment]
@relyativist - yes. a simpler command is:

```shell
$ docker build -t ants:v.2.3.1 --build-arg ants_version="v2.3.1" - < Dockerfile
```

where `v2.3.1` is the version to build in this case.

**Comment by yarkinslav** [comment]
@kaczmarj , nah, now it has:
     ```
---> Running in 54f231f3901b
ERROR: ants_version or ants_git_hash not defined
```

**Comment by kaczmarj** [comment]
@relyativist - i think you did not checkout the branch `add/versions` before running the `docker build` command.

**Comment by yarkinslav** [comment]
@kaczmarj yes! sorry, my fault
